[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r server/requirements.txt"
]

[start]
cmd = "python -m uvicorn server.main:app --host 0.0.0.0 --port ${PORT:-8000}"
